### PR TITLE
index layout

### PR DESCRIPTION
**Pull request by YitingTinaRen**
Hi PengPeng,

I am 任頤庭.
Please help me to review my result!
There are many requirements, hope I did not miss any of them.
The address is http://52.37.59.29:3000/
Let me know if there is anything to be fixed.
Thank you.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Initialize category block as hidden one. Don't show a blank one at start.
2. left-padding of keyword input should not be 0.
3. Aspect ratio of any images in your page should keep the same as original ones.

**Comment by YitingTinaRen** [comment]
Hello PengPeng,

I have updated the codes to fix the 3 you named.
Could you please help to check and review the result again?
http://52.37.59.29:3000/
Thank you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Final one issue I just noticed. Footer position should not always fix in the bottom.

**Comment by YitingTinaRen** [comment]
Hello PengPeng!

I also fix footer position to make it disappear when scrolling.
In addition, I also found that I did not froze the nav bar, so fixed this as well.
Please have a review of new updates.
Thanks.
http://52.37.59.29:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
But we do have a footer in the page bottom, just do not always fix in the bottom of screen.

**Comment by YitingTinaRen** [comment]
Hi PengPeng,

Now I get your point.
The footer is now set to be at the end of content rather than at the bottom of the screen.
Thank you!
The updated result: http://52.37.59.29:3000/

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
