### PR TITLE
working attraction apis

### PR DESCRIPTION
**Pull request by YitingTinaRen**
任頤庭
Check on my local computer, the 3 apis can work.

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
You should deploy your code to EC2 Instance. Paste live URLs for checking.

**Comment by YitingTinaRen** [comment]
ahh! I see!
I think I made a mistake.
I shall pull the files on github on develop branch rather than main branch!

**Comment by YitingTinaRen** [comment]
Hello Peng Peng:

I'd like to hand in the hw of this week
working attraction api urls:
http://52.37.59.29:3000/api/attractions
http://52.37.59.29:3000/api/attraction/1
http://52.37.59.29:3000/api/categories

Please help to review it.
Thanks.

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by YitingTinaRen** [comment]
Re-review request is sent!
Thanks!

**Review by cwpeng — CHANGES_REQUESTED** [review]
Fix issues below and re-request review.

1. http://52.37.59.29:3000/api/categories should response category names without repetition.
2. Use keyword to filter attraction category and name, not description.
3. It's much better to use `LIMIT` in SQL to do pagination than do it in your own code.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
