### PR TITLE
member page

### PR DESCRIPTION
**Pull request by YitingTinaRen**
Hi Peng Peng,

Please help to check if the member page is ok or not!
The web page is in the following link:
http://52.37.59.29:3000/

I have managed to complete it! lol
Thank you!

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Web server is down for now.

**Comment by YitingTinaRen** [comment]
Sorry I forgot to make nohop command.
Now the server is running!
Thanks!

**Review by cwpeng — COMMENTED** [review]
I try to upload new picture but cannot show it after I refresh page.

**Comment by YitingTinaRen** [comment]
I fixed the upload issue!
Please take a look at the resolution!
Thank you!
http://52.37.59.29:3000/

**Review by cwpeng — APPROVED** [review]
Good. You have done many improvements in this project. It's time to go forward to our next striking one. :)

**Pull request merged**
