### PR TITLE
Account api and UI

### PR DESCRIPTION
**Pull request by YitingTinaRen**
PengPeng good evening!

I am 任頤庭!
Could you help me to check my week 4 hw results?
http://52.37.59.29:3000/
Thank you.

Best regards,
Tina

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Your server is down for now.

**Comment by YitingTinaRen** [comment]
Sorry for this mistake!
The server issue is fixed!
Please take your time to check it!
http://52.37.59.29:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by YitingTinaRen** [comment]
Thank you!!

**Pull request merged**
